name: word_jumble
description: A new Flutter project.
publish_to: "none"
version: 0.1.0





environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  go_router: ^6.2.0
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logging: ^1.1.1
  one_context: ^4.0.0
  path_provider: ^2.1.4
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/lvl1/
    - assets/images/lvl2/
    - assets/images/lvl3/
    - assets/sound/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: DarlingCoffee
      fonts:
        - asset: assets/fonts/Darling-Coffee.ttf
    - family: BatmanForeverAlternate
      fonts:
        - asset: assets/fonts/Batman-Forever.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21